// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NBALigaSimulation.Server.Data;

#nullable disable

namespace NBALigaSimulation.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230702153350_TeamRegularStats")]
    partial class TeamRegularStats
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.FAOffer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Response")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Season")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Years")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TeamId");

                    b.ToTable("FAOffers");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("GameDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Happened")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeasonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("SeasonId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.GamePlayByPlay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameSimId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("T")
                        .HasColumnType("REAL");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("PlayByPlays");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Hgt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pos")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("PtModifier")
                        .HasColumnType("REAL");

                    b.Property<int>("RosterOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.PlayerContract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Exp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("PlayerContracts");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.PlayerGameStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ast")
                        .HasColumnType("INTEGER");

                    b.Property<double>("BenchTime")
                        .HasColumnType("REAL");

                    b.Property<int>("Blk")
                        .HasColumnType("INTEGER");

                    b.Property<double>("CourtTime")
                        .HasColumnType("REAL");

                    b.Property<int>("Drb")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Energy")
                        .HasColumnType("REAL");

                    b.Property<int>("Fg")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FgAtRim")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FgLowPost")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FgMidRange")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Fga")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FgaAtRim")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FgaLowPost")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FgaMidRange")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ft")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Fta")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Gs")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Min")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Orb")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Pf")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Pts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Season")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stl")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tov")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tpa")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Trb")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerGameStats");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.PlayerRatings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Blk")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Dnk")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Drb")
                        .HasColumnType("INTEGER");

                    b.Property<int>("End")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Fg")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ft")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Hgt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ins")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Jmp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Pot")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Pss")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Reb")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Season")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Spd")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stl")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Str")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerRatings");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Abrv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Conference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsHuman")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.TeamDraftPicks", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Original")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Round")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("TeamDraftPicks");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.TeamGameStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ast")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Blk")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Drb")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Fg")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FgAtRim")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FgLowPost")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FgMidRange")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Fga")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FgaAtRim")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FgaLowPost")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FgaMidRange")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ft")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Fta")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Min")
                        .HasColumnType("REAL");

                    b.Property<int>("Orb")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Pf")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Pts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Season")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stl")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tov")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tpa")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Trb")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("TeamId");

                    b.ToTable("TeamGameStats");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.TeamGameplan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Defense")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Focus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Motion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Pace")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TeamId")
                        .IsUnique();

                    b.ToTable("TeamGameplans");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.TeamRegularStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Allowed3PA")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Allowed3PM")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AllowedAssists")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AllowedBlocks")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AllowedFGA")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AllowedFGM")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AllowedFTA")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AllowedFTM")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AllowedPoints")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AllowedRebounds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AllowedStealS")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AllowedTurnovers")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Assists")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Blocks")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConfRank")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FGA")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FGM")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FTA")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FTM")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HomeLosses")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HomeWins")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayoffLosses")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayoffWins")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Points")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rebounds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoadLosses")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoadWins")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Season")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Steals")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TPA")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TPM")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Turnovers")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TeamId")
                        .IsUnique();

                    b.ToTable("TeamRegularStats");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.Trade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Response")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamOneId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamTwoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TeamOneId");

                    b.HasIndex("TeamTwoId");

                    b.ToTable("Trades");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.TradePicks", b =>
                {
                    b.Property<int>("DraftPickId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TradePickId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DraftPickId", "TradePickId");

                    b.HasIndex("TradePickId");

                    b.ToTable("TradePicks");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.TradePlayer", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TradePlayerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlayerId", "TradePlayerId");

                    b.HasIndex("TradePlayerId");

                    b.ToTable("TradePlayer");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCreated")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int?>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TeamId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.FAOffer", b =>
                {
                    b.HasOne("NBALigaSimulation.Shared.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NBALigaSimulation.Shared.Models.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.Game", b =>
                {
                    b.HasOne("NBALigaSimulation.Shared.Models.Team", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NBALigaSimulation.Shared.Models.Team", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NBALigaSimulation.Shared.Models.Season", "Season")
                        .WithMany("Games")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.GamePlayByPlay", b =>
                {
                    b.HasOne("NBALigaSimulation.Shared.Models.Game", "Game")
                        .WithMany("PlayByPlay")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.Player", b =>
                {
                    b.HasOne("NBALigaSimulation.Shared.Models.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("NBALigaSimulation.Shared.Models.Born", "Born", b1 =>
                        {
                            b1.Property<int>("PlayerId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Loc")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("Year")
                                .HasColumnType("INTEGER");

                            b1.HasKey("PlayerId");

                            b1.ToTable("Players");

                            b1.WithOwner()
                                .HasForeignKey("PlayerId");
                        });

                    b.Navigation("Born")
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.PlayerContract", b =>
                {
                    b.HasOne("NBALigaSimulation.Shared.Models.Player", "Player")
                        .WithOne("Contract")
                        .HasForeignKey("NBALigaSimulation.Shared.Models.PlayerContract", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.PlayerGameStats", b =>
                {
                    b.HasOne("NBALigaSimulation.Shared.Models.Game", "Game")
                        .WithMany("PlayerGameStats")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NBALigaSimulation.Shared.Models.Player", null)
                        .WithMany("Stats")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.PlayerRatings", b =>
                {
                    b.HasOne("NBALigaSimulation.Shared.Models.Player", "Player")
                        .WithMany("Ratings")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.TeamDraftPicks", b =>
                {
                    b.HasOne("NBALigaSimulation.Shared.Models.Team", "Team")
                        .WithMany("DraftPicks")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.TeamGameStats", b =>
                {
                    b.HasOne("NBALigaSimulation.Shared.Models.Game", "Game")
                        .WithMany("TeamGameStats")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NBALigaSimulation.Shared.Models.Team", null)
                        .WithMany("Stats")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.TeamGameplan", b =>
                {
                    b.HasOne("NBALigaSimulation.Shared.Models.Team", "Team")
                        .WithOne("Gameplan")
                        .HasForeignKey("NBALigaSimulation.Shared.Models.TeamGameplan", "TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.TeamRegularStats", b =>
                {
                    b.HasOne("NBALigaSimulation.Shared.Models.Team", "Team")
                        .WithOne("TeamRegularStats")
                        .HasForeignKey("NBALigaSimulation.Shared.Models.TeamRegularStats", "TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.Trade", b =>
                {
                    b.HasOne("NBALigaSimulation.Shared.Models.Team", "TeamOne")
                        .WithMany()
                        .HasForeignKey("TeamOneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NBALigaSimulation.Shared.Models.Team", "TeamTwo")
                        .WithMany()
                        .HasForeignKey("TeamTwoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TeamOne");

                    b.Navigation("TeamTwo");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.TradePicks", b =>
                {
                    b.HasOne("NBALigaSimulation.Shared.Models.TeamDraftPicks", "DraftPick")
                        .WithMany()
                        .HasForeignKey("DraftPickId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NBALigaSimulation.Shared.Models.Trade", "Trade")
                        .WithMany("TradePicks")
                        .HasForeignKey("TradePickId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DraftPick");

                    b.Navigation("Trade");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.TradePlayer", b =>
                {
                    b.HasOne("NBALigaSimulation.Shared.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NBALigaSimulation.Shared.Models.Trade", "Trade")
                        .WithMany("TradePlayers")
                        .HasForeignKey("TradePlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Trade");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.User", b =>
                {
                    b.HasOne("NBALigaSimulation.Shared.Models.Team", "Team")
                        .WithOne()
                        .HasForeignKey("NBALigaSimulation.Shared.Models.User", "TeamId");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.Game", b =>
                {
                    b.Navigation("PlayByPlay");

                    b.Navigation("PlayerGameStats");

                    b.Navigation("TeamGameStats");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.Player", b =>
                {
                    b.Navigation("Contract");

                    b.Navigation("Ratings");

                    b.Navigation("Stats");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.Season", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.Team", b =>
                {
                    b.Navigation("DraftPicks");

                    b.Navigation("Gameplan")
                        .IsRequired();

                    b.Navigation("Players");

                    b.Navigation("Stats");

                    b.Navigation("TeamRegularStats")
                        .IsRequired();
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.Trade", b =>
                {
                    b.Navigation("TradePicks");

                    b.Navigation("TradePlayers");
                });
#pragma warning restore 612, 618
        }
    }
}
