// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NBALigaSimulation.Server.Data;

#nullable disable

namespace NBALigaSimulation.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230518224108_addPlayByPly")]
    partial class addPlayByPly
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.GamePlayByPlay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameSimId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("T")
                        .HasColumnType("REAL");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameSimId");

                    b.ToTable("PlayByPlays");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BornYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PtModifier")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RosterOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.PlayerGameStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ast")
                        .HasColumnType("INTEGER");

                    b.Property<double>("BenchTime")
                        .HasColumnType("REAL");

                    b.Property<int>("Blk")
                        .HasColumnType("INTEGER");

                    b.Property<double>("CourtTime")
                        .HasColumnType("REAL");

                    b.Property<int>("Drb")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Energy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Fg")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FgAtRim")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FgLowPost")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FgMidRange")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Fga")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FgaAtRim")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FgaLowPost")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FgaMidRange")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ft")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Fta")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Gs")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Min")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Orb")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Pf")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Pts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stl")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tov")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tpa")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Trb")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerGameStats");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.PlayerRatings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Blk")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Dnk")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Drb")
                        .HasColumnType("INTEGER");

                    b.Property<int>("End")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Fg")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ft")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Hgt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ins")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Jmp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Pss")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Reb")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Season")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Spd")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stl")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Str")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.PtsQtr", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Points")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuarterNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamGameStatsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TeamGameStatsId");

                    b.ToTable("PtsQtrs");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Abrv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.TeamGameStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ast")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Blk")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Drb")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Fg")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FgAtRim")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FgLowPost")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FgMidRange")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Fga")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FgaAtRim")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FgaLowPost")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FgaMidRange")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ft")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Fta")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Min")
                        .HasColumnType("REAL");

                    b.Property<int>("Orb")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Pf")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Pts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Season")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stl")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tov")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tpa")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Trb")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("TeamId");

                    b.ToTable("TeamGameStats");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.Game", b =>
                {
                    b.HasOne("NBALigaSimulation.Shared.Models.Team", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NBALigaSimulation.Shared.Models.Team", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.GamePlayByPlay", b =>
                {
                    b.HasOne("NBALigaSimulation.Shared.Models.Game", "Game")
                        .WithMany("PlayByPlay")
                        .HasForeignKey("GameSimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.Player", b =>
                {
                    b.HasOne("NBALigaSimulation.Shared.Models.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.PlayerGameStats", b =>
                {
                    b.HasOne("NBALigaSimulation.Shared.Models.Game", "Game")
                        .WithMany("PlayerGameStats")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NBALigaSimulation.Shared.Models.Player", null)
                        .WithMany("Stats")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.PlayerRatings", b =>
                {
                    b.HasOne("NBALigaSimulation.Shared.Models.Player", "Player")
                        .WithMany("Ratings")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.PtsQtr", b =>
                {
                    b.HasOne("NBALigaSimulation.Shared.Models.TeamGameStats", "TeamGameStats")
                        .WithMany("PtsQtrs")
                        .HasForeignKey("TeamGameStatsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TeamGameStats");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.TeamGameStats", b =>
                {
                    b.HasOne("NBALigaSimulation.Shared.Models.Game", "Game")
                        .WithMany("TeamGameStats")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NBALigaSimulation.Shared.Models.Team", null)
                        .WithMany("Stats")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.Game", b =>
                {
                    b.Navigation("PlayByPlay");

                    b.Navigation("PlayerGameStats");

                    b.Navigation("TeamGameStats");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.Player", b =>
                {
                    b.Navigation("Ratings");

                    b.Navigation("Stats");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.Team", b =>
                {
                    b.Navigation("Players");

                    b.Navigation("Stats");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.TeamGameStats", b =>
                {
                    b.Navigation("PtsQtrs");
                });
#pragma warning restore 612, 618
        }
    }
}
