// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NBALigaSimulation.Server.Data;

#nullable disable

namespace NBALigaSimulation.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230510214504_Game")]
    partial class Game
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AwayOT")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AwayQ1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AwayQ2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AwayQ3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AwayQ4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HomeOT")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HomeQ1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HomeQ2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HomeQ3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HomeQ4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.GamePlayByPlay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Play")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("GamePlayByPlay");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BornYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.PlayerRatings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Blk")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Dnk")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Drb")
                        .HasColumnType("INTEGER");

                    b.Property<int>("End")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Fg")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ft")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Hgt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ins")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Jmp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Pss")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Reb")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Season")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Spd")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stl")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Str")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Abrv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.Game", b =>
                {
                    b.HasOne("NBALigaSimulation.Shared.Models.Team", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NBALigaSimulation.Shared.Models.Team", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.GamePlayByPlay", b =>
                {
                    b.HasOne("NBALigaSimulation.Shared.Models.Game", null)
                        .WithMany("PlayByPlays")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.Player", b =>
                {
                    b.HasOne("NBALigaSimulation.Shared.Models.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.PlayerRatings", b =>
                {
                    b.HasOne("NBALigaSimulation.Shared.Models.Player", "Player")
                        .WithMany("Ratings")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.Game", b =>
                {
                    b.Navigation("PlayByPlays");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.Player", b =>
                {
                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.Team", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
