// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NBALigaSimulation.Server.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NBALigaSimulation.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.Drafts.Draft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Original")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Pick")
                        .HasColumnType("integer");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("Round")
                        .HasColumnType("integer");

                    b.Property<int>("Season")
                        .HasColumnType("integer");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TeamId");

                    b.ToTable("Drafts");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.Drafts.DraftLottery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FifthTeam")
                        .HasColumnType("text");

                    b.Property<int>("FifthTeamId")
                        .HasColumnType("integer");

                    b.Property<string>("FirstTeam")
                        .HasColumnType("text");

                    b.Property<int>("FirstTeamId")
                        .HasColumnType("integer");

                    b.Property<string>("FourthTeam")
                        .HasColumnType("text");

                    b.Property<int>("FourthTeamId")
                        .HasColumnType("integer");

                    b.Property<int>("Season")
                        .HasColumnType("integer");

                    b.Property<string>("SecondTeam")
                        .HasColumnType("text");

                    b.Property<int>("SecondTeamId")
                        .HasColumnType("integer");

                    b.Property<string>("SixthTeam")
                        .HasColumnType("text");

                    b.Property<int>("SixthTeamId")
                        .HasColumnType("integer");

                    b.Property<string>("ThirdTeam")
                        .HasColumnType("text");

                    b.Property<int>("ThirdTeamId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("DraftLotteries");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.FA.FAOffer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<bool?>("Response")
                        .HasColumnType("boolean");

                    b.Property<int>("Season")
                        .HasColumnType("integer");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<int>("Years")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TeamId");

                    b.ToTable("FAOffers");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.GameNews.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("GameId")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<int?>("LinkEntityId")
                        .HasColumnType("integer");

                    b.Property<string>("LinkEntityType")
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<string>("Winner")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GameNews");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.Games.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("GameDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Happened")
                        .HasColumnType("boolean");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("integer");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("Week")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("SeasonId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.Players.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("College")
                        .HasColumnType("text");

                    b.Property<int>("Hgt")
                        .HasColumnType("integer");

                    b.Property<string>("ImgUrl")
                        .HasColumnType("text");

                    b.Property<int?>("InjuryGamesRemaining")
                        .HasColumnType("integer");

                    b.Property<string>("InjuryType")
                        .HasColumnType("text");

                    b.Property<bool>("KeyPlayer")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Pos")
                        .HasColumnType("text");

                    b.Property<double>("PtModifier")
                        .HasColumnType("double precision");

                    b.Property<int>("RosterOrder")
                        .HasColumnType("integer");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.Players.PlayerAwardCounts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AllStarGames")
                        .HasColumnType("integer");

                    b.Property<int>("DPOY")
                        .HasColumnType("integer");

                    b.Property<int>("MIP")
                        .HasColumnType("integer");

                    b.Property<int>("MVP")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerOfTheGame")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerOfTheMonth")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerOfTheWeek")
                        .HasColumnType("integer");

                    b.Property<int>("ROY")
                        .HasColumnType("integer");

                    b.Property<int>("SixthManOfTheYear")
                        .HasColumnType("integer");

                    b.Property<int>("TitlesWon")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("PlayerAwardCounts");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.Players.PlayerAwards", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apg")
                        .HasColumnType("text");

                    b.Property<string>("Award")
                        .HasColumnType("text");

                    b.Property<string>("Bpg")
                        .HasColumnType("text");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<string>("Ppg")
                        .HasColumnType("text");

                    b.Property<string>("Rpg")
                        .HasColumnType("text");

                    b.Property<int>("Season")
                        .HasColumnType("integer");

                    b.Property<string>("Spg")
                        .HasColumnType("text");

                    b.Property<string>("Team")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerAwards");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.Players.PlayerContract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<int>("Exp")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("PlayerContracts");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.Players.PlayerGameStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Ast")
                        .HasColumnType("integer");

                    b.Property<double>("BenchTime")
                        .HasColumnType("double precision");

                    b.Property<int>("Blk")
                        .HasColumnType("integer");

                    b.Property<double>("CourtTime")
                        .HasColumnType("double precision");

                    b.Property<int>("Drb")
                        .HasColumnType("integer");

                    b.Property<double>("Energy")
                        .HasColumnType("double precision");

                    b.Property<int>("Fg")
                        .HasColumnType("integer");

                    b.Property<int>("FgAtRim")
                        .HasColumnType("integer");

                    b.Property<int>("FgLowPost")
                        .HasColumnType("integer");

                    b.Property<int>("FgMidRange")
                        .HasColumnType("integer");

                    b.Property<int>("Fga")
                        .HasColumnType("integer");

                    b.Property<int>("FgaAtRim")
                        .HasColumnType("integer");

                    b.Property<int>("FgaLowPost")
                        .HasColumnType("integer");

                    b.Property<int>("FgaMidRange")
                        .HasColumnType("integer");

                    b.Property<int>("Ft")
                        .HasColumnType("integer");

                    b.Property<int>("Fta")
                        .HasColumnType("integer");

                    b.Property<DateTime>("GameDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<int>("Gs")
                        .HasColumnType("integer");

                    b.Property<double>("Min")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("OppAbrev")
                        .HasColumnType("text");

                    b.Property<int>("Orb")
                        .HasColumnType("integer");

                    b.Property<int>("Pf")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<string>("Pos")
                        .HasColumnType("text");

                    b.Property<int>("Pts")
                        .HasColumnType("integer");

                    b.Property<int>("Season")
                        .HasColumnType("integer");

                    b.Property<int>("Stl")
                        .HasColumnType("integer");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<int>("Tov")
                        .HasColumnType("integer");

                    b.Property<int>("Tp")
                        .HasColumnType("integer");

                    b.Property<int>("Tpa")
                        .HasColumnType("integer");

                    b.Property<int>("Trb")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerGameStats");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.Players.PlayerPlayoffsStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Ast")
                        .HasColumnType("integer");

                    b.Property<int>("Blk")
                        .HasColumnType("integer");

                    b.Property<int>("Drb")
                        .HasColumnType("integer");

                    b.Property<int>("Fg")
                        .HasColumnType("integer");

                    b.Property<int>("FgAtRim")
                        .HasColumnType("integer");

                    b.Property<int>("FgLowPost")
                        .HasColumnType("integer");

                    b.Property<int>("FgMidRange")
                        .HasColumnType("integer");

                    b.Property<int>("Fga")
                        .HasColumnType("integer");

                    b.Property<int>("FgaAtRim")
                        .HasColumnType("integer");

                    b.Property<int>("FgaLowPost")
                        .HasColumnType("integer");

                    b.Property<int>("FgaMidRange")
                        .HasColumnType("integer");

                    b.Property<int>("Ft")
                        .HasColumnType("integer");

                    b.Property<int>("Fta")
                        .HasColumnType("integer");

                    b.Property<int>("Games")
                        .HasColumnType("integer");

                    b.Property<int>("Gs")
                        .HasColumnType("integer");

                    b.Property<double>("Min")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Orb")
                        .HasColumnType("integer");

                    b.Property<int>("Pf")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("Pts")
                        .HasColumnType("integer");

                    b.Property<int>("Season")
                        .HasColumnType("integer");

                    b.Property<int>("Stl")
                        .HasColumnType("integer");

                    b.Property<string>("TeamAbrv")
                        .HasColumnType("text");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<int>("Tov")
                        .HasColumnType("integer");

                    b.Property<int>("Tp")
                        .HasColumnType("integer");

                    b.Property<int>("Tpa")
                        .HasColumnType("integer");

                    b.Property<int>("Trb")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerPlayoffsStats");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.Players.PlayerRatings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Diq")
                        .HasColumnType("integer");

                    b.Property<int>("Dnk")
                        .HasColumnType("integer");

                    b.Property<int>("Drb")
                        .HasColumnType("integer");

                    b.Property<int>("Endu")
                        .HasColumnType("integer");

                    b.Property<int>("Fg")
                        .HasColumnType("integer");

                    b.Property<int>("Ft")
                        .HasColumnType("integer");

                    b.Property<int>("Hgt")
                        .HasColumnType("integer");

                    b.Property<int>("Ins")
                        .HasColumnType("integer");

                    b.Property<int>("Jmp")
                        .HasColumnType("integer");

                    b.Property<int>("Oiq")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("Pot")
                        .HasColumnType("integer");

                    b.Property<int>("Pss")
                        .HasColumnType("integer");

                    b.Property<int>("Reb")
                        .HasColumnType("integer");

                    b.Property<string>("ScoutReport")
                        .HasColumnType("text");

                    b.Property<int>("Season")
                        .HasColumnType("integer");

                    b.Property<int>("Spd")
                        .HasColumnType("integer");

                    b.Property<int>("Stre")
                        .HasColumnType("integer");

                    b.Property<int>("Tp")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerRatings");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.Players.PlayerRegularStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Ast")
                        .HasColumnType("integer");

                    b.Property<int>("Blk")
                        .HasColumnType("integer");

                    b.Property<int>("Drb")
                        .HasColumnType("integer");

                    b.Property<int>("Fg")
                        .HasColumnType("integer");

                    b.Property<int>("FgAtRim")
                        .HasColumnType("integer");

                    b.Property<int>("FgLowPost")
                        .HasColumnType("integer");

                    b.Property<int>("FgMidRange")
                        .HasColumnType("integer");

                    b.Property<int>("Fga")
                        .HasColumnType("integer");

                    b.Property<int>("FgaAtRim")
                        .HasColumnType("integer");

                    b.Property<int>("FgaLowPost")
                        .HasColumnType("integer");

                    b.Property<int>("FgaMidRange")
                        .HasColumnType("integer");

                    b.Property<int>("Ft")
                        .HasColumnType("integer");

                    b.Property<int>("Fta")
                        .HasColumnType("integer");

                    b.Property<int>("Games")
                        .HasColumnType("integer");

                    b.Property<int>("Gs")
                        .HasColumnType("integer");

                    b.Property<double>("Min")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Orb")
                        .HasColumnType("integer");

                    b.Property<int>("Pf")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<string>("Pos")
                        .HasColumnType("text");

                    b.Property<int>("Pts")
                        .HasColumnType("integer");

                    b.Property<int>("Season")
                        .HasColumnType("integer");

                    b.Property<int>("Stl")
                        .HasColumnType("integer");

                    b.Property<string>("TeamAbrv")
                        .HasColumnType("text");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<int>("Tov")
                        .HasColumnType("integer");

                    b.Property<int>("Tp")
                        .HasColumnType("integer");

                    b.Property<int>("Tpa")
                        .HasColumnType("integer");

                    b.Property<int>("Trb")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerRegularStats");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.SeasonPlayoffs.Playoffs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Complete")
                        .HasColumnType("boolean");

                    b.Property<int>("Season")
                        .HasColumnType("integer");

                    b.Property<int>("SeriesId")
                        .HasColumnType("integer");

                    b.Property<int>("TeamOneId")
                        .HasColumnType("integer");

                    b.Property<int>("TeamTwoId")
                        .HasColumnType("integer");

                    b.Property<int>("WinsTeamOne")
                        .HasColumnType("integer");

                    b.Property<int>("WinsTeamTwo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TeamOneId");

                    b.HasIndex("TeamTwoId");

                    b.ToTable("Playoffs");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.SeasonPlayoffs.PlayoffsGame", b =>
                {
                    b.Property<int>("PlayoffsId")
                        .HasColumnType("integer");

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.HasKey("PlayoffsId", "GameId");

                    b.HasIndex("GameId");

                    b.ToTable("PlayoffGames");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.Seasons.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("DeadlineCompleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("DraftCompleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("FirstRoundCompleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("FourthRoundCompleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("LotteryCompleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("RegularCompleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("SecondRoundCompleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("TcCompleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("ThirdRoundCompleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.Teams.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Abrv")
                        .HasColumnType("text");

                    b.Property<int>("Championships")
                        .HasColumnType("integer");

                    b.Property<string>("Conference")
                        .HasColumnType("text");

                    b.Property<bool>("IsHuman")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.Teams.TeamDraftPicks", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Original")
                        .HasColumnType("text");

                    b.Property<int>("Round")
                        .HasColumnType("integer");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("Original", "Year", "Round")
                        .IsUnique();

                    b.ToTable("TeamDraftPicks");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.Teams.TeamGameStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Ast")
                        .HasColumnType("integer");

                    b.Property<int>("Blk")
                        .HasColumnType("integer");

                    b.Property<int>("Drb")
                        .HasColumnType("integer");

                    b.Property<int>("Fg")
                        .HasColumnType("integer");

                    b.Property<int>("FgAtRim")
                        .HasColumnType("integer");

                    b.Property<int>("FgLowPost")
                        .HasColumnType("integer");

                    b.Property<int>("FgMidRange")
                        .HasColumnType("integer");

                    b.Property<int>("Fga")
                        .HasColumnType("integer");

                    b.Property<int>("FgaAtRim")
                        .HasColumnType("integer");

                    b.Property<int>("FgaLowPost")
                        .HasColumnType("integer");

                    b.Property<int>("FgaMidRange")
                        .HasColumnType("integer");

                    b.Property<int>("Ft")
                        .HasColumnType("integer");

                    b.Property<int>("Fta")
                        .HasColumnType("integer");

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<double>("Min")
                        .HasColumnType("double precision");

                    b.Property<int>("Orb")
                        .HasColumnType("integer");

                    b.Property<int>("Pf")
                        .HasColumnType("integer");

                    b.Property<int>("Pts")
                        .HasColumnType("integer");

                    b.Property<int>("Season")
                        .HasColumnType("integer");

                    b.Property<int>("Stl")
                        .HasColumnType("integer");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<int>("Tov")
                        .HasColumnType("integer");

                    b.Property<int>("Tp")
                        .HasColumnType("integer");

                    b.Property<int>("Tpa")
                        .HasColumnType("integer");

                    b.Property<int>("Trb")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("TeamId");

                    b.ToTable("TeamGameStats");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.Teams.TeamGameplan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Defense")
                        .HasColumnType("integer");

                    b.Property<int>("Focus")
                        .HasColumnType("integer");

                    b.Property<int>("Motion")
                        .HasColumnType("integer");

                    b.Property<int>("Pace")
                        .HasColumnType("integer");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TeamId")
                        .IsUnique();

                    b.ToTable("TeamGameplans");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.Teams.TeamPlayoffsStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Allowed3PA")
                        .HasColumnType("integer");

                    b.Property<int>("Allowed3PM")
                        .HasColumnType("integer");

                    b.Property<int>("AllowedAssists")
                        .HasColumnType("integer");

                    b.Property<int>("AllowedBlocks")
                        .HasColumnType("integer");

                    b.Property<int>("AllowedFGA")
                        .HasColumnType("integer");

                    b.Property<int>("AllowedFGM")
                        .HasColumnType("integer");

                    b.Property<int>("AllowedFTA")
                        .HasColumnType("integer");

                    b.Property<int>("AllowedFTM")
                        .HasColumnType("integer");

                    b.Property<int>("AllowedPoints")
                        .HasColumnType("integer");

                    b.Property<int>("AllowedRebounds")
                        .HasColumnType("integer");

                    b.Property<int>("AllowedStealS")
                        .HasColumnType("integer");

                    b.Property<int>("AllowedTurnovers")
                        .HasColumnType("integer");

                    b.Property<int>("Assists")
                        .HasColumnType("integer");

                    b.Property<int>("Blocks")
                        .HasColumnType("integer");

                    b.Property<int>("ConfRank")
                        .HasColumnType("integer");

                    b.Property<int>("FGA")
                        .HasColumnType("integer");

                    b.Property<int>("FGM")
                        .HasColumnType("integer");

                    b.Property<int>("FTA")
                        .HasColumnType("integer");

                    b.Property<int>("FTM")
                        .HasColumnType("integer");

                    b.Property<int>("PlayoffLosses")
                        .HasColumnType("integer");

                    b.Property<int>("PlayoffWins")
                        .HasColumnType("integer");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<int>("Rebounds")
                        .HasColumnType("integer");

                    b.Property<int>("Season")
                        .HasColumnType("integer");

                    b.Property<int>("Steals")
                        .HasColumnType("integer");

                    b.Property<int>("TPA")
                        .HasColumnType("integer");

                    b.Property<int>("TPM")
                        .HasColumnType("integer");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<int>("Turnovers")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("TeamPlayoffsStats");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.Teams.TeamRegularStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Allowed3PA")
                        .HasColumnType("integer");

                    b.Property<int>("Allowed3PM")
                        .HasColumnType("integer");

                    b.Property<int>("AllowedAssists")
                        .HasColumnType("integer");

                    b.Property<int>("AllowedBlocks")
                        .HasColumnType("integer");

                    b.Property<int>("AllowedFGA")
                        .HasColumnType("integer");

                    b.Property<int>("AllowedFGM")
                        .HasColumnType("integer");

                    b.Property<int>("AllowedFTA")
                        .HasColumnType("integer");

                    b.Property<int>("AllowedFTM")
                        .HasColumnType("integer");

                    b.Property<int>("AllowedFouls")
                        .HasColumnType("integer");

                    b.Property<int>("AllowedPoints")
                        .HasColumnType("integer");

                    b.Property<int>("AllowedRebounds")
                        .HasColumnType("integer");

                    b.Property<int>("AllowedStealS")
                        .HasColumnType("integer");

                    b.Property<int>("AllowedTurnovers")
                        .HasColumnType("integer");

                    b.Property<int>("Assists")
                        .HasColumnType("integer");

                    b.Property<int>("Blocks")
                        .HasColumnType("integer");

                    b.Property<int>("ConfRank")
                        .HasColumnType("integer");

                    b.Property<int>("FGA")
                        .HasColumnType("integer");

                    b.Property<int>("FGM")
                        .HasColumnType("integer");

                    b.Property<int>("FTA")
                        .HasColumnType("integer");

                    b.Property<int>("FTM")
                        .HasColumnType("integer");

                    b.Property<int>("Fouls")
                        .HasColumnType("integer");

                    b.Property<int>("HomeLosses")
                        .HasColumnType("integer");

                    b.Property<int>("HomeWins")
                        .HasColumnType("integer");

                    b.Property<int>("PlayoffLosses")
                        .HasColumnType("integer");

                    b.Property<int>("PlayoffWins")
                        .HasColumnType("integer");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<int>("Rebounds")
                        .HasColumnType("integer");

                    b.Property<int>("RoadLosses")
                        .HasColumnType("integer");

                    b.Property<int>("RoadWins")
                        .HasColumnType("integer");

                    b.Property<int>("Season")
                        .HasColumnType("integer");

                    b.Property<int>("Steals")
                        .HasColumnType("integer");

                    b.Property<int>("Streak")
                        .HasColumnType("integer");

                    b.Property<int>("TPA")
                        .HasColumnType("integer");

                    b.Property<int>("TPM")
                        .HasColumnType("integer");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<int>("Turnovers")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("TeamRegularStats");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.Trades.Trade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("Response")
                        .HasColumnType("boolean");

                    b.Property<int>("TeamOneId")
                        .HasColumnType("integer");

                    b.Property<int>("TeamTwoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TeamOneId");

                    b.HasIndex("TeamTwoId");

                    b.ToTable("Trades");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.Trades.TradePicks", b =>
                {
                    b.Property<int>("DraftPickId")
                        .HasColumnType("integer");

                    b.Property<int>("TradePickId")
                        .HasColumnType("integer");

                    b.HasKey("DraftPickId", "TradePickId");

                    b.HasIndex("TradePickId");

                    b.ToTable("TradePicks");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.Trades.TradePlayer", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("TradePlayerId")
                        .HasColumnType("integer");

                    b.HasKey("PlayerId", "TradePlayerId");

                    b.HasIndex("TradePlayerId");

                    b.ToTable("TradePlayer");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("bytea");

                    b.Property<int?>("TeamId")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TeamId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.Drafts.Draft", b =>
                {
                    b.HasOne("NBALigaSimulation.Shared.Models.Players.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("NBALigaSimulation.Shared.Models.Teams.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.FA.FAOffer", b =>
                {
                    b.HasOne("NBALigaSimulation.Shared.Models.Players.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NBALigaSimulation.Shared.Models.Teams.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.Games.Game", b =>
                {
                    b.HasOne("NBALigaSimulation.Shared.Models.Teams.Team", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NBALigaSimulation.Shared.Models.Teams.Team", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NBALigaSimulation.Shared.Models.Seasons.Season", "Season")
                        .WithMany("Games")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.Players.Player", b =>
                {
                    b.HasOne("NBALigaSimulation.Shared.Models.Teams.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("NBALigaSimulation.Shared.Models.Players.Born", "Born", b1 =>
                        {
                            b1.Property<int>("PlayerId")
                                .HasColumnType("integer");

                            b1.Property<string>("Loc")
                                .HasColumnType("text");

                            b1.Property<int>("Year")
                                .HasColumnType("integer");

                            b1.HasKey("PlayerId");

                            b1.ToTable("Players");

                            b1.WithOwner()
                                .HasForeignKey("PlayerId");
                        });

                    b.OwnsOne("NBALigaSimulation.Shared.Models.Players.PlayerDraft", "Draft", b1 =>
                        {
                            b1.Property<int>("PlayerId")
                                .HasColumnType("integer");

                            b1.Property<int>("Pick")
                                .HasColumnType("integer");

                            b1.Property<int>("Round")
                                .HasColumnType("integer");

                            b1.Property<string>("Team")
                                .HasColumnType("text");

                            b1.Property<int>("Year")
                                .HasColumnType("integer");

                            b1.HasKey("PlayerId");

                            b1.ToTable("Players");

                            b1.WithOwner()
                                .HasForeignKey("PlayerId");
                        });

                    b.Navigation("Born");

                    b.Navigation("Draft");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.Players.PlayerAwardCounts", b =>
                {
                    b.HasOne("NBALigaSimulation.Shared.Models.Players.Player", "Player")
                        .WithOne("AwardCounts")
                        .HasForeignKey("NBALigaSimulation.Shared.Models.Players.PlayerAwardCounts", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.Players.PlayerAwards", b =>
                {
                    b.HasOne("NBALigaSimulation.Shared.Models.Players.Player", "Player")
                        .WithMany("PlayerAwards")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.Players.PlayerContract", b =>
                {
                    b.HasOne("NBALigaSimulation.Shared.Models.Players.Player", "Player")
                        .WithOne("Contract")
                        .HasForeignKey("NBALigaSimulation.Shared.Models.Players.PlayerContract", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.Players.PlayerGameStats", b =>
                {
                    b.HasOne("NBALigaSimulation.Shared.Models.Games.Game", "Game")
                        .WithMany("PlayerGameStats")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NBALigaSimulation.Shared.Models.Players.Player", "Player")
                        .WithMany("Stats")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.Players.PlayerPlayoffsStats", b =>
                {
                    b.HasOne("NBALigaSimulation.Shared.Models.Players.Player", "Player")
                        .WithMany("PlayoffsStats")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.Players.PlayerRatings", b =>
                {
                    b.HasOne("NBALigaSimulation.Shared.Models.Players.Player", "Player")
                        .WithMany("Ratings")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.Players.PlayerRegularStats", b =>
                {
                    b.HasOne("NBALigaSimulation.Shared.Models.Players.Player", "Player")
                        .WithMany("RegularStats")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.SeasonPlayoffs.Playoffs", b =>
                {
                    b.HasOne("NBALigaSimulation.Shared.Models.Teams.Team", "TeamOne")
                        .WithMany()
                        .HasForeignKey("TeamOneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NBALigaSimulation.Shared.Models.Teams.Team", "TeamTwo")
                        .WithMany()
                        .HasForeignKey("TeamTwoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TeamOne");

                    b.Navigation("TeamTwo");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.SeasonPlayoffs.PlayoffsGame", b =>
                {
                    b.HasOne("NBALigaSimulation.Shared.Models.Games.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NBALigaSimulation.Shared.Models.SeasonPlayoffs.Playoffs", "Playoffs")
                        .WithMany("PlayoffGames")
                        .HasForeignKey("PlayoffsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Playoffs");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.Teams.TeamDraftPicks", b =>
                {
                    b.HasOne("NBALigaSimulation.Shared.Models.Teams.Team", "Team")
                        .WithMany("DraftPicks")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.Teams.TeamGameStats", b =>
                {
                    b.HasOne("NBALigaSimulation.Shared.Models.Games.Game", "Game")
                        .WithMany("TeamGameStats")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NBALigaSimulation.Shared.Models.Teams.Team", null)
                        .WithMany("Stats")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.Teams.TeamGameplan", b =>
                {
                    b.HasOne("NBALigaSimulation.Shared.Models.Teams.Team", "Team")
                        .WithOne("Gameplan")
                        .HasForeignKey("NBALigaSimulation.Shared.Models.Teams.TeamGameplan", "TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.Teams.TeamPlayoffsStats", b =>
                {
                    b.HasOne("NBALigaSimulation.Shared.Models.Teams.Team", "Team")
                        .WithMany("TeamPlayoffsStats")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.Teams.TeamRegularStats", b =>
                {
                    b.HasOne("NBALigaSimulation.Shared.Models.Teams.Team", "Team")
                        .WithMany("TeamRegularStats")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.Trades.Trade", b =>
                {
                    b.HasOne("NBALigaSimulation.Shared.Models.Teams.Team", "TeamOne")
                        .WithMany()
                        .HasForeignKey("TeamOneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NBALigaSimulation.Shared.Models.Teams.Team", "TeamTwo")
                        .WithMany()
                        .HasForeignKey("TeamTwoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TeamOne");

                    b.Navigation("TeamTwo");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.Trades.TradePicks", b =>
                {
                    b.HasOne("NBALigaSimulation.Shared.Models.Teams.TeamDraftPicks", "DraftPick")
                        .WithMany()
                        .HasForeignKey("DraftPickId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NBALigaSimulation.Shared.Models.Trades.Trade", "Trade")
                        .WithMany("TradePicks")
                        .HasForeignKey("TradePickId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DraftPick");

                    b.Navigation("Trade");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.Trades.TradePlayer", b =>
                {
                    b.HasOne("NBALigaSimulation.Shared.Models.Players.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NBALigaSimulation.Shared.Models.Trades.Trade", "Trade")
                        .WithMany("TradePlayers")
                        .HasForeignKey("TradePlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Trade");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.Users.User", b =>
                {
                    b.HasOne("NBALigaSimulation.Shared.Models.Teams.Team", "Team")
                        .WithOne()
                        .HasForeignKey("NBALigaSimulation.Shared.Models.Users.User", "TeamId");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.Games.Game", b =>
                {
                    b.Navigation("PlayerGameStats");

                    b.Navigation("TeamGameStats");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.Players.Player", b =>
                {
                    b.Navigation("AwardCounts");

                    b.Navigation("Contract");

                    b.Navigation("PlayerAwards");

                    b.Navigation("PlayoffsStats");

                    b.Navigation("Ratings");

                    b.Navigation("RegularStats");

                    b.Navigation("Stats");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.SeasonPlayoffs.Playoffs", b =>
                {
                    b.Navigation("PlayoffGames");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.Seasons.Season", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.Teams.Team", b =>
                {
                    b.Navigation("DraftPicks");

                    b.Navigation("Gameplan");

                    b.Navigation("Players");

                    b.Navigation("Stats");

                    b.Navigation("TeamPlayoffsStats");

                    b.Navigation("TeamRegularStats");
                });

            modelBuilder.Entity("NBALigaSimulation.Shared.Models.Trades.Trade", b =>
                {
                    b.Navigation("TradePicks");

                    b.Navigation("TradePlayers");
                });
#pragma warning restore 612, 618
        }
    }
}
